export const MCP_PROMPT_METADATA = 'MCP_PROMPT_METADATA';
export const MCP_TOOL_METADATA = 'MCP_TOOL_METADATA';
export const MCP_TOOL_WITH_PARAMS_METADATA = 'MCP_TOOL_WITH_PARAMS_METADATA';
// 👇 Thêm 2 dòng này
export const MCP_RESOURCE_METADATA = 'MCP_RESOURCE_METADATA';
export const MCP_RESOURCE_TEMPLATE_METADATA = 'MCP_RESOURCE_TEMPLATE_METADATA';
export const MCP_IS_PUBLIC = 'MCP_IS_PUBLIC';
